# Generated by Django 2.1.7 on 2019-04-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highscore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoresmodel',
            name='user',
            field=models.CharField(default='AWichmann', max_length=50),
        ),
    ]
